// Kuratierte Auswahl Rollatoren — alle leicht, faltbar, mit Sitz, Tasche, Bremsen.
// Stand: 2026-05-04. Kontext: Oma 85, Schulter-Reha, Ostsee-Urlaub, BYD Seal U Touring.
// Hinweis: Preis & technische Specs sind nur Robins Daten — werden nicht in Omas Wizard angezeigt.
window.__ROLLATORS_DATA__ = [
  {
    id: 'letsgo',
    brand: 'Trust Care',
    name: "Let's Go Out",
    trait: 'Sportlich-schlicht, kompakt',
    price: 275,
    weight: 6.2,
    foldedSize: '19 × 64 × 77 cm',
    maxLoad: 130,
    material: 'Aluminium',
    seat: true,
    basket: true,
    seatHeight: 60,
    colors: ['schwarz', 'beige'],
    pros: 'Schmalstes Faltmaß (19 cm). Große Räder für Promenadenpflaster. Günstigster Preis.',
    url: 'https://www.sanitaets-online.de/mobilitaet/rollatoren/outdoor-rollator/1008/trust-care-outdoor-rollator-let-s-go-out-schwarz/silber',
    image: './assets/rollators/trustcare-letsgo-out.webp',
  },
  {
    id: 'russka',
    brand: 'Russka',
    name: 'Vital Carbon',
    trait: 'Modern und sehr leicht (Carbon)',
    price: 339,
    weight: 5.7,
    foldedSize: '23 × 60 × 66 cm',
    maxLoad: 150,
    material: 'Carbon',
    seat: true,
    basket: true,
    seatHeight: 62,
    colors: ['schwarz'],
    pros: 'Stiftung-Warentest-Mitsieger 2019. Magnetischer Faltmechanismus.',
    url: 'https://www.seeger24.de/Russka-Vital-Carbon-Rollator/0000028247.01',
    image: './assets/rollators/russka-vital-carbon.webp',
  },
  {
    id: 'topro',
    brand: 'Topro',
    name: 'Troja 2G Premium',
    trait: 'Klassisch und sehr robust',
    price: 337,
    weight: 7.8,
    foldedSize: '24 × 81 × 66 cm',
    maxLoad: 150,
    material: 'Aluminium',
    seat: true,
    basket: true,
    seatHeight: 62,
    colors: ['anthrazit', 'silber', 'weiß', 'kirsch', 'blau'],
    pros: 'Stiftung-Warentest-Testsieger 03/2019. Norwegische Wertarbeit. Ergonomische Griffe.',
    url: 'https://www.sanitaets-online.de/mobilitaet/rollatoren/leichtgewicht-rollator/581/topro-rollator-troja-2g-m-premium-dunkelgrau',
    image: './assets/rollators/topro-troja-2g.webp',
  },
  {
    id: 'letsfly',
    brand: 'Trust Care',
    name: "Let's Fly",
    trait: 'Schick, mit Federung',
    price: 383,
    weight: 6.8,
    foldedSize: '24,5 × 65,5 × 78,5 cm',
    maxLoad: 130,
    material: 'Aluminium',
    seat: true,
    basket: true,
    seatHeight: 60,
    colors: ['rot', 'beige', 'grau', 'weiß'],
    pros: 'Designpreis. Stabiles Aluminium-Gestell mit Federung.',
    url: 'https://www.sanitaets-online.de/mobilitaet/rollatoren/leichtgewicht-rollator/1620/trust-care-rollator-let-s-fly-rot',
    image: './assets/rollators/trustcare-letsfly.webp',
  },
];
